### ISSUE TITLE
Decoding on Linux

### ISSUE THREAD

**Issue by jwattik** [hermanTenuki/imageZIP#1]
Decoding on Linux does not work correctly from a terminal running in the home directory. 
Preconditions:
1. Ubuntu

> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.1 LTS
> Release:        20.04
> Codename:       focal

2. pip install imageZIP

Steps:
1. Save picture to home directory (https://github.com/hermanTenuki/imageZIP/raw/main/.github/demo_zip.png)
2. Open Terminal and start python console
3. Use suggested command to decode an image `imageZIP.unzip("demo_zip.png", scale=4)`

Expected result, all files are unpacked into one folder called imageZIP
The actual result, all the file is unpacked into the home directory with the names of the path where they should have been stored
![Screenshot_20201125_125259](https://user-images.githubusercontent.com/22703789/100188624-279ba180-2f1d-11eb-9a61-86a08c0c5cb4.png)

**Comment by hermanTenuki** [comment]
Thanks for the detailed issue, i am very sorry for the bug, i just simply forgot to test it on Linux. Should be working after upcoming #2  (v2) update.

**Comment by jwattik** [comment]
It's okay :) The implementation of the idea is very good.
